# Generated by Django 2.2.4 on 2019-08-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0002_auto_20190824_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilesFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_api.UserProfile')),
            ],
        ),
    ]
